### ISSUE TITLE
The split linker script wrong

### ISSUE THREAD

**Issue by ronios1989** [Decawave/mynewt-dw1000-core#1]
In the hw/bsp/dwm1001/bsp.yml file:
bsp.part2linkerscript: "hw/bsp/dwm1001/split-nrf52-thingy.ld"  --> split-nrf52.ld

If use the mynewt splitty, can't open split-nrf52-thingy.ld, it's may be split-nrf52.ld in this floder.
If this one is not right, can copy the mynewt-core/hw/bsp/nrf52dk/split-nrf52dk.ld file.

**Comment by pkettle** [comment]
Hi Ronios,

**Comment by pkettle** [comment]
Hi Ronios,
Thanks for this, 
I believe the bsp.yml should read as you indicate. I will merge your changes. Regards Paul
bsp.part2linkerscript: "hw/bsp/dwm1001/split-nrf52.ld"
