### ISSUE TITLE
About the skew calculation in rng.c

### ISSUE THREAD

**Issue by ftianf** [Decawave/mynewt-dw1000-core#13]
In rng.c there are two ways to calculate the skew (https://github.com/Decawave/mynewt-dw1000-core/blob/master/lib/rng/src/rng.c#L648-L653) , if WCS is enabled then skew calculation is based on prediction from timescale lib, otherwise it's based on instantaneous register value. Is the timescale one more accurate than the register one?

**Comment by ncasaril** [comment]
The WCS is more accurate and the register value (carrier integrator) isn't available when using double buffered rx.
