### ISSUE TITLE
risk overflow associated with uint32_t type of repeat_dly

### ISSUE THREAD

**Issue by flacordaire** [Decawave/mynewt-dw1000-core#16]
Hi, 
in rtdoa_node.c line 365 
risk overflow associated with uint32_t type of repeat_dly
Instead of 
(repeat_dly << 16)*(1.0l - wcs->skew)
Shouldn't it be sth like : 
frame->rpt_count*((uint64_t)rtdoa->config.tx_holdoff_dly<<16)*(1.0l - wcs->skew)
as further below when computing tx_timestamp (line 374)?

**Comment by ncasaril** [comment]
Hi, 

Thanks for your suggestion. In theory you're absolutely correct. In practice though the relay would have to be over 65ms (65536us) delayed before the field would overflow. 
The relay of rtdoa_node is in reality not tested yet and this also highlighted that the rx_timestamp compensation by just adding up the holdoffs isn't correct. 

Thanks,
N
